version: "3.8"
services:
  web:
    build: ./app
    image: 561755087467.dkr.ecr.us-east-1.amazonaws.com/final_project:final_project_web
    command: gunicorn tours_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=tours_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=saturday-1.cqpgs841dnna.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-34-204-64-78.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 561755087467.dkr.ecr.us-east-1.amazonaws.com/final_project:final_project_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
